PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop'] # Invoke within Bundler context
  BundleOutdated:
    enabled: true
  BundleAudit:
    enabled: true
PrePush:
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec', '-f', 'p'] # Invoke within Bundler context
