# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `bin/tapioca require`.

# typed: false

require 'active_support/core_ext/string/inflections'
require 'bundler/setup'
require 'dotenv/load'
require 'faker'
require 'faraday'
require 'forwardable'
require 'json'
require 'ostruct'
require 'ripper'
require 'rspec_in_context'
require 'simplecov'
require 'socket'
require 'vcr'
require 'zeitwerk'
