name: Tests

on:
  push:
    branches-ignore: 
      - main

jobs:
  tests:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install yarn dep
      run: yarn install
    - name: Check prettier
      run: yarn prettier -c '**/*.rb' 
