name: Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.6, 2.7, '3.0']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
      - name: Run type checking (Sorbet)
        run: bundle exec srb tc
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn dep
        run: yarn install
      - name: Check prettier
        run: yarn prettier -c '**/*.rb'
